import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-300">
        <header className="bg-white shadow-sm">
          <div className="max-w-6xl mx-auto p-4 flex justify-between">
            <Link href="/" className="font-bold text-xl">
              Mini Blog App
            </Link>
            <nav className="flex gap-4">
              <Link
                href="/posts/create"
                className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition"
              >
                + New Post
              </Link>
            </nav>
          </div>
        </header>
        <main className="max-w-4xl mx-auto p-6 my-12">{children}</main>
        <footer className="bg-white w-full text-center text-gray-500 text-sm fixed bottom-0 p-3">
          © 2026 Mini Blog App
        </footer>
      </body>
    </html>
  )
}
