import type { Metadata } from 'next'
import './globals.css'
import ToastProvider from '../components/L2/toast/ToastProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <header>Header</header>
        <main>
          {children}
          <ToastProvider />
        </main>
        <footer>Footer</footer>
      </body>
    </html>
  )
}
