import type { Metadata } from 'next'
import './globals.css'

import ToastProvider from '../components/L2/toast/ToastProvider'
import Header from '../components/layouts/Header'
import Footer from '../components/layouts/Footer'
import { LoadingSpinner } from '../components/L2/loading/loading'
import { LoadingProvider } from '../context/LoadingContext'

export const metadata: Metadata = {
  title: 'My Mini Blog App',
  description: 'Generated by VinhNguyen',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-300">
        <LoadingProvider>
          <Header />
          <main className="max-w-4xl mx-auto p-6 mb-10">
            <LoadingSpinner />
            {children}
            <ToastProvider />
          </main>
          <Footer />
        </LoadingProvider>
      </body>
    </html>
  )
}
